version: '3.8'
services:
  wacrm:
    image: luisluce/wacrm:latest
    container_name: wacrm_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
